### ISSUE TITLE
使用RSA_NO_PADDING时，报错。

### ISSUE THREAD

**Issue by liuyuanpeng** [myafer/OpenSSLApplication#2]
当PADDING改为RSA_NO_PADDING时，RSA_Public_Encrypt() 会返回-1.
需要怎么解决呢？

**Comment by myafer** [comment]
这个的填充方式不一样，需要再写下

**Comment by myafer** [comment]
具体可以参考：http://openssl.6102.n7.nabble.com/RSA-private-encrypt-does-not-work-with-RSA-NO-PADDING-option-td28763.html
